export const Images = {
  splash_01: require('./img_splash_01.png'),
  splash_02: require('./img_splash_02.png'),
  splash_03: require('./img_splash_03.png'),
  empty_wallet: require('./img_empty_wallet.png'),
  netflix: require('./img_netflix.png'),
  rounded: require('./img_rounded.png'),
  avatar_01: require('./img_avatar_01.png'),
  take_photo: require('./img_take_photo.png'),
  photo_01: require('./img_photo_01.png'),
  photo_02: require('./img_photo_02.png'),
  photo_03: require('./img_photo_03.png'),
  photo_04: require('./img_photo_04.png'),
  photo_05: require('./img_photo_05.png'),
  photo_06: require('./img_photo_06.png'),
  photo_07: require('./img_photo_07.png'),
  wallet_delete: require('./img_wallet_delete.png'),
  cash_wallet: require('./img_cash_wallet.png'),
  success: require('./img_success.png'),
  budget: require('./img_budget.png'),
  firework: require('./img_firework.png'),
  ads_banner: require('./img_adbanner.png'),
  hotdog:require('./img_hotdog.png'),
};
